spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/ioumeibing/SpringcloudConfig.git
          searchPaths: respo
          force-pull: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/